### ISSUE TITLE
Status of compose commands

### ISSUE THREAD

**Issue by ivantsepp** [jekyll/jekyll-compose#1]
Seems like the discussion around incorporating drafts, post, pages command cooled off recently. I was wondering if there was still interest in this. Looking at https://github.com/jekyll/jekyll/pull/2378, I think it's just a matter of opening a new PR against this repo with the same code. @BennyHallett were you still planning on making a PR? If not, I would be more than happy to help (of course, I would still label those commits as you being the author).

**Comment by campo** [comment]
Hey guys, I know I'm a complete noob here, but figured I check in on this. Can it be closed given that the pull request mentioned was merged?

Are there any other issues that I might be able to help out on? This is the only one open.

Thanks!
campo

**Comment by parkr** [comment]
Thanks, @campo! This can be closed.

If you find ways to improve the tool, please send a pull request! One idea we've had is templates for new posts/pages.
