### ISSUE TITLE
If `collections_dir` is not set, `arg_parser` raises exception

### ISSUE THREAD

**Issue by ttilberg** [jekyll/jekyll-compose#112]
I just tried installing this gem into a Jekyll 3.5.2 app, and had issues with:

```
TypeError: no implicit conversion of nil into String
  /Users/ttilberg/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-compose-0.9.0/lib/jekyll-compose/arg_parser.rb:36:in `join'
```

This line is trying to `File.join` a `nil` argument if `collections_dir` is not set.

```ruby
        File.join(config["source"], config["collections_dir"])
```

**Comment by ashmaroli** [comment]
This was resolved in subsequent versions by locking to minimum Jekyll 3.7.0
For your use-case, you'll have to downgrade to v0.8.0 of this plugin or use a newer Jekyll version.

**Comment by ttilberg** [comment]
Hm. I wonder why bundler and gemspec didn't sort that out as expected. I see that you do in fact have bundler specifying Jekyll >= 3.7.

Thanks for the note.

**Comment by ashmaroli** [comment]
Unfortunately, v0.9.0 of this plugin which introduced the support for `collections_dir` has no such lock: https://rubygems.org/gems/jekyll-compose/versions/0.9.0

**Comment by ttilberg** [comment]
Ahhh, makes sense. Maybe we could just add a small note to the readme about compatibility? 

Thanks for your work, this is great. I've been using a sublime plugin but always have to reconfigure it on new clones.
