### ISSUE TITLE
compase commands are not registered in jekyll

### ISSUE THREAD

**Issue by lancevo** [jekyll/jekyll-compose#12]
I installed the latest jekyll-composed, and even added code below in Gemfile, jekyll still doesn't recognize `draft`, `post`, etc... The error came back is `invalid command`
```ruby
group :jekyll_plugins do
  gem 'jekyll-compose'
end
```

**Comment by parkr** [comment]
If you run `jekyll -h`, what do you see?

**Comment by lancevo** [comment]
I see the usual commands such as `build`,`serve`,etc.. but I don't see
`draft`,`post`,`publish`.

**Comment by parkr** [comment]
And when you run `bundle exec jekyll -h`? What version of Jekyll?

**Comment by lancevo** [comment]
It returns the same message. I'm using version 2.4.0

**Comment by parkr** [comment]
> I'm using version 2.4.0

v2.4.0 doesn't autoload commands. :( If you upgrade, you'll be good!
