### ISSUE TITLE
jekyll help does not show jekyll-compose commands; Mac OSX: gem 2.4.5: jekyll 2.5.3: jekyll-compose 0.2.1: 

### ISSUE THREAD

**Issue by mhminai** [jekyll/jekyll-compose#13]
I am unable to get the jekyll-compose commands to run. Specifically I tried "jekyll draft" and I got:
Invalid command. Use --help for more information
When I look up jekyll help, I do not see the "draft", "post" or "publish" commands.
gem list --local shows me the following versions of relevant gems:
jekyll (2.5.3, 2.4.0)
jekyll-coffeescript (1.0.1)
jekyll-compose (0.2.1)
jekyll-gist (1.1.0)
jekyll-import (0.5.3)
jekyll-mentions (0.2.1)
jekyll-paginate (1.1.0)
jekyll-redirect-from (0.6.2)
jekyll-sass-converter (1.3.0, 1.2.0)
jekyll-sitemap (0.6.3)
jekyll-watch (1.2.1)

Not too sure, what I am doing wrong.

**Comment by mhminai** [comment]
p.s. I installed jekyll-compose with:
gem install jekyll-compose

**Comment by elipapa** [comment]
same here. I also tried to add the group to the Gemfile as suggested:

    group :jekyll_plugins do
        gem 'jekyll-compose'
    end

but it did not help.

**Comment by christian-fei** [comment]
Same here

**Comment by parkr** [comment]
you need to add `jekyll-compose` to your gemfile as @elipapa indicated, then use `bundle exec jekyll <command>`.

**Comment by christian-fei** [comment]
Thanks.
Already added jekyll-compose to my Gemfile,
and invoked the command with bundle, still getting

```
Invalid command. Use --help for more information
````

**Comment by christian-fei** [comment]
using Jekyll 2.5.3

**Comment by elipapa** [comment]
same here. unfortunately `bundle exec jekyll <command>` does not help.

**Comment by parkr** [comment]
Oh, sorry guys. I think this only works with the new Jekyll 3 beta.

**Comment by jasper-lyons** [comment]
Would it not be sensible to note the dependance on the Readme to prevent more people from falling at this hurdle?

**Comment by parkr** [comment]
> Would it not be sensible to note the dependance on the Readme to prevent more people from falling at this hurdle?

Yes, it would be very sensible. Would you propose an update with a pull request, please?

**Comment by jasper-lyons** [comment]
I will indeed

**Comment by jasper-lyons** [comment]
#14 is the pull request with the updated readme.

Is there anything we can do for jekyll < 3 beta users?

**Comment by parkr** [comment]
No, the code that brings in these commands isn't in 2.x.

Thanks for the PR!
