### ISSUE TITLE
Add generator for create pages

### ISSUE THREAD

**Issue by nmenag** [jekyll/jekyll-compose#15]

**Comment by FellowMD** [comment]
@parkr do you want to include this? The PR build failed due to a bug in the specs, but it'd be easy to pull in.

**Comment by parkr** [comment]
Depends on the implementation. Should be simple and should align with the post generator as much as possible.

**Comment by FellowMD** [comment]
It looked completely in line with the post generator to me. I'll fix the specs and give it a once over
