### ISSUE TITLE
Commands fail with opaque error when _posts does not exist

### ISSUE THREAD

**Issue by FellowMD** [jekyll/jekyll-compose#17]
Running a `jekyll publish`, or `jekyll post` when _posts does not exist results in errors looking like this:
`jekyll 2.5.3 | Error:  No such file or directory @ sys_fail2 - (_drafts/my-site.md, _posts/2015-06-07-my-site.md)`
I think it should create the folder, or at least display an informative error instead.

**Comment by parkr** [comment]
> I think it should create the folder, or at least display an informative error instead.

Let's have it create the folder! Would you mind submitting a PR?

**Comment by FellowMD** [comment]
Sure I'll give it a shot



— Aaron Sikes
