### ISSUE TITLE
0.3.0 release

### ISSUE THREAD

**Issue by AaronSikes** [jekyll/jekyll-compose#20]
@parkr Would you create a new release with the new page generation functionality?

**Comment by FellowMD** [comment]
Note the history.md is a little inaccurate at the moment, since I added an 0.2.2 entry which was never released.

**Comment by parkr** [comment]
Would you mind refactoring to reduce code duplication.

**Comment by FellowMD** [comment]
Sure

**Comment by FellowMD** [comment]
@parkr Refactor done, and other things as well. A release would be great. All changes are in History.md

**Comment by tongueroo** [comment]
+1 for this. I did not see unpublish command in the jekyll-compose 0.2.1 version.  @AaronSikes where is the pull request for the refactor?

**Comment by AaronSikes** [comment]
The refactor was in #24 and has been merged.
@parkr imo we're good for a release. Just update history.markdown & version.rb & push to rubygems

**Comment by parkr** [comment]
https://github.com/jekyll/jekyll-compose/releases/tag/v0.3.0

**Comment by tongueroo** [comment]
@parkr Thanks for getting that done so quickly :exclamation:
