### ISSUE TITLE
Add unpublish  command

### ISSUE THREAD

**Issue by nmenag** [jekyll/jekyll-compose#21]
would be good implement the command unpublish for the posts,    for a post and convert it into a draft.

**Comment by parkr** [comment]
There is also a "published" flag... I am not sure what most Jekyll users would prefer. drafts, or the published yaml front matter flag?

**Comment by FellowMD** [comment]
I think moving back to drafts makes more sense. Makes it the proper inverse of the publish command.
There could be a retract command or something similar if anyone wants that, but that is very easy to do manually. I see jekyll compose mostly as a tool for avoiding typing dates in the filenames, or having to type _awkward _underscore _dirs.

**Comment by parkr** [comment]
:cool: :+1:

**Comment by nmenag** [comment]
equal to Octopress: 

New draft https://github.com/octopress/octopress#new-draft  
Publish draft https://github.com/octopress/octopress#publish-a-draft 
And unpublish post  https://github.com/octopress/octopress#unpublish-a-post

**Comment by FellowMD** [comment]
That's probably a pretty good thing? This is supposed to be lighter-weight, and doesn't add any artifacts to your project.

**Comment by FellowMD** [comment]
Added by #26
