### ISSUE TITLE
Drop leading ./ from messages & errors?

### ISSUE THREAD

**Issue by FellowMD** [jekyll/jekyll-compose#22]
I personally think the message
`New post created at _posts/2015-06-19-thingy.md.`
would be a bit nicer than
`New post created at ./_posts/2015-06-19-thingy.md.`

The command is only valid from one directory anyway (the root of the jekyll project)

Thoughts?

**Comment by parkr** [comment]
If you run it within a subdirectory in your site, what does it print out? I don't think it matters that much.

**Comment by FellowMD** [comment]
```bash
$ cd my-site/subdir
$ jekyll post blah
Invalid command. Use --help for more information
```
I didn't think it would matter, but I've never really dealt with public facing CLI's before. Just checking.
I don't like it as is, because the `./` is being prepended manually, rather than coming from some Path method or system call. Seems like it might end up being a lie at some point so I'd rather remove it.

**Comment by parkr** [comment]
Ok cool
