### ISSUE TITLE
-t overshadowed by jekyll built-in -t

### ISSUE THREAD

**Issue by FellowMD** [jekyll/jekyll-compose#25]
`-t` is already claimed by the `--trace` option. We should choose another short flag or remove it, since it doesn't work as documented.

**Comment by FellowMD** [comment]
I'm thinking `-m` `--markup` would be good. We could also use either `-e` or `-x` with `--extension`, or just drop `-t` and leave the `--type` long flag.

**Comment by parkr** [comment]
I like both!

**Comment by FellowMD** [comment]
Fixed in eca6e26ad995ac7bc51fa0ea3b7d192ee6557f05
