### ISSUE TITLE
jekyll-compose doesn't show up in help, commands don't work.

### ISSUE THREAD

**Issue by nguillermin** [jekyll/jekyll-compose#27]
gem install jekyll-compose
    Successfully installed jekyll-compose-0.2.1
    Parsing documentation for jekyll-compose-0.2.1
    Done installing documentation for jekyll-compose after 0 seconds
    1 gem installed
=>

    jekyll help
    jekyll 2.4.0 -- Jekyll is a blog-aware, static site generator in Ruby

    Usage:

      jekyll <subcommand> [options]

    Options:
            -s, --source [DIR]  Source directory (defaults to ./)
            -d, --destination [DIR]  Destination directory (defaults to ./_site)
                --safe         Safe mode (defaults to false)
            -p, --plugins PLUGINS_DIR1[,PLUGINS_DIR2[,...]]  Plugins directory (defaults to ./_plugins)
                --layouts DIR  Layouts directory (defaults to ./_layouts)
            -h, --help         Show this message
            -v, --version      Print the name and version
            -t, --trace        Show the full backtrace when an error occurs

    Subcommands:
      build                 Build your site
      docs                  Launch local server with docs for Jekyll v2.4.0
      doctor, hyde          Search site and print specific deprecation warnings
      help                  Show the help message, optionally for a given subcommand.
      new                   Creates a new Jekyll site scaffold in PATH
      serve, server         Serve your site locally
=>

    jekyll draft
    Invalid command. Use --help for more information

:(

Only thing I can think of is it looks like jekyll-compose requires rake and I *do* have it in my /usr/local/bin but Gem list doesn't list it so I assume it got there some other way (It is 10.4.2 though).

**Comment by parkr** [comment]
Did you try the "Helpful Note" from the readme? Do that then use `bundle exec jekyll help`

**Comment by nguillermin** [comment]
No change. Gemfile, if that helps.

    source "https://rubygems.org"

    gem 'github-pages'
    group :jekyll_plugins do
      gem 'jekyll-compose'
    end

**Comment by tongueroo** [comment]
@nguillermin you need to update your version of jekyll , I ran into the same issue and upgrading to jekyll 2.5.3 fixed it.  Basically the code to load plugins does not exist on version 2.4.0

**Comment by Haroenv** [comment]
I have `jekyll 2.5.3` and I still experience this issue

**Comment by tongueroo** [comment]
@Haroenv weird are you sure you're on jekyll 2.5.3?  and you have 

```ruby
source "https://rubygems.org"
gem 'github-pages'
group :jekyll_plugins do
  gem 'jekyll-compose'
end
```

What I did to find this out was that I went into https://github.com/jekyll/jekyll/blob/master/lib/jekyll/plugin_manager.rb#L35 and modified it so that it'll throw an error to make sure that I'm loading the right version of Jekyll:

```ruby
    def self.require_from_bundler
      raise "the roof"
      if !ENV["JEKYLL_NO_BUNDLER_REQUIRE"] && File.file?("Gemfile")
        require "bundler"
```

You can use `bundle show jekyll` to find out where your jekyll version is installed.

Hope that helps.

**Comment by emaiax** [comment]
I ran into the same issue.

After finding out that `github-pages-39` forces me to use `jekyll-2.4.0`, I removed it from my `Gemfile`, updated `jekyll-2.5.3` and everything started to work. :+1:

**Comment by nguillermin** [comment]
After uninstalling jekyll-2.4.0 and making sure I added jekyll-compose in my jekyll-plugins groups, it works.

Thanks all.
