### ISSUE TITLE
Command not available; unresolved specs

### ISSUE THREAD

**Issue by ndarville** [jekyll/jekyll-compose#28]
```sh
$ bundle exec jekyll post
Invalid command. Use --help for more information 

$ jekyll post
WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      listen (~> 2.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Users/ndarville/.rbenv/versions/2.2.0-dev/lib/ruby/gems/2.3.0/gems/jekyll-2.5.3/bin/jekyll:21:in `block in <top (required)>': cannot load such file -- jekyll/version (LoadError)
    from /Users/ndarville/.rbenv/versions/2.2.0-dev/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'
    from /Users/ndarville/.rbenv/versions/2.2.0-dev/lib/ruby/gems/2.3.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
    from /Users/ndarville/.rbenv/versions/2.2.0-dev/bin/jekyll:23:in `load'
    from /Users/ndarville/.rbenv/versions/2.2.0-dev/bin/jekyll:23:in `<main>’
```

I’ve tried both using `jekyll-compose` in my Gemfile as well as a gem in `_config.yml` with the same result.

**Comment by parkr** [comment]
Did you try Jekyll 3?

**Comment by ndarville** [comment]
Ah, I thought github-pages 39 was already Jekyll 3.

**Comment by indianajs** [comment]
Hi, stumbled upon the same error, did an upgrade to 3.0.pre.beta8 and now i still have this error

```
>> bundle exec jekyll draft
Invalid command. Use --help for more information 

>> jekyll draft "IoT Compass with IndianaJS"
WARN: Unresolved specs during Gem::Specification.reset:
      listen (~> 2.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Invalid command. Use --help for more information
```

Gemfile:
```
gem 'github-pages', versions['github-pages']
gem 'jekyll-compose'

group :jekyll_plugins do
  gem 'jekyll-compose'
end
```

**Comment by indianajs** [comment]
Sorry, my mistake.

I had both 2.4.0 and 2.5.3 installed and was using the gh-pages gem.
It seems that version 39 of gh-pages still uses 2.4.0 so that was installed as my main version.

**Comment by exalted** [comment]
I was trying to get this working as well. What's the final verdict here? GitHub pages does indeed run `jekyll 2.4.0`, but why is that even an issue with this plugin I don't understand.

Feedback kindly requested. :wink:

**Comment by parkr** [comment]
@exalted The feature to add automatic plugin loading for plugins with commands wasn't added until 2.5.0: jekyll/jekyll#2865.

**Comment by exalted** [comment]
@parkr Oh, that makes sense!

What _was_ the _old way_ of doind things _back then_ please? :wine_glass:

**Comment by parkr** [comment]
> What was the old way of doind things back then please?

The old way was to generate your own command, like `jekyll-compose` or `jekyll-draft` and calling it directly. This plugin doesn't support that, sadly.

**Comment by exalted** [comment]
@parkr thanks for the feedback. I guess I will cross my fingers for GitHub to update to at least `2.5.0`

**Comment by parkr** [comment]
> @parkr thanks for the feedback. I guess I will cross my fingers for GitHub to update to at least 2.5.0

We're releasing 3.0 this week and they should be able to upgrade sometime soon. I have heard that they are taking a look at it as we speak. I'll work with any contacts I have there to try to make 3.0 a reality on Pages as soon as we can.

In the meantime, you can use 2.5.3 locally as it's very similar to 2.4.0.

**Comment by exalted** [comment]
@parkr great! :clap:

**Comment by MasterRoot24** [comment]
I just got caught out by this :disappointed: 

@parkr Do you think we could add this to the readme so that newcomers know that they need Jekyll >=2.5.0 for this gem to actually do anything?

**Comment by exalted** [comment]
:+1:

--
Ali




On Sun, Nov 1, 2015 at 5:36 AM -0800, "Joe Nyland" <notifications@github.com> wrote:












I just got caught out by this  



@parkr Do you think we could add this to the readme so that newcomers know that they need Jekyll >=2.5.0 for this gem to actually do anything?

**Comment by parkr** [comment]
> @parkr Do you think we could add this to the readme so that newcomers know that they need Jekyll >=2.5.0 for this gem to actually do anything?

Great idea, sorry that's so confusing.

**Comment by exalted** [comment]
More on this: would it be too crazy to specify this gem to depend on `jekyll` at least `>= 2.5.0` rather than current `>= 2.0`?

**Comment by parkr** [comment]
@exalted great idea!
