### ISSUE TITLE
Does it work with `github-pages` gem?

### ISSUE THREAD

**Issue by Ashton-W** [jekyll/jekyll-compose#36]
I can't get this working with the `github-pages` gem, which is just a gem that pins jekyll and some extra dependencies to match the versions running on GitHub Pages.

My `Gemfile` looks like this:

```ruby
source 'https://rubygems.org'

gem 'jekyll-compose'
gem 'github-pages'
```

Using bundler but the new commands from compose are not being installed. What am I missing?

**Comment by parkr** [comment]
Hey @Ashton-W! No, unfortunately this doesn't currently work with github-pages, because `jekyll-compose` requires Jekyll v2.5.0 or higher and github-pages uses 2.4.0. Subscribe to github/pages-gem#175 to be kept in the loop regarding the Jekyll 3 upgrade!

**Comment by lpil** [comment]
gh-pages has Jekyll > v2.5.0 now, but this gem seems not to work. What's the status here?
