### ISSUE TITLE
I cannot see the compose commands

### ISSUE THREAD

**Issue by blackjid** [jekyll/jekyll-compose#4]
I added the gem to the `gemfile`

``` rb
gem 'jekyll-compose'
```

this to the `_config.yml`

``` yaml
gems:
  - jekyll-compose
```

runned `bundle install`

and when I try `jekyll --help` or `bundle exec jekyll --help` I cannot see any of the composer commands...

I also tried adding this to the gemfile

``` rb
group :jekyll_plugins do
  gem "jekyll-compose"
end
```

any idea??

thanks

**Comment by 0a-** [comment]
@parkr I think you mean Jekyll 2.5 ([Commands are introduced in 2.5](http://jekyllrb.com/docs/plugins/#commands)) Or is there any chance that you are using some 3.0 feature?
