### ISSUE TITLE
Configure default layout?

### ISSUE THREAD

**Issue by dsolodow** [jekyll/jekyll-compose#65]
Started to kick the tires with this gem, and I noticed that new drafts/posts are created with layout:post

My theme uses a different layout for posts; is there a way to have jekyll-compose default to that different layout? I'm guessing it would be something in _config.yml?

**Comment by DirtyF** [comment]
Th
```sh
jekyll post --help

jekyll post -- Creates a new post with the given NAME

Usage:

  jekyll post NAME

Options:
-x EXTENSION, --extension EXTENSION  Specify the file extension
 -l LAYOUT, --layout LAYOUT  Specify the post layout
 -f, --force        Overwrite a post if it already exists
 -d DATE, --date DATE    Specify the post date
```

**Comment by dsolodow** [comment]
But there isn't a way to make a different layout the default via a config file/setting? Would just have to always include the --layout argument?
