### ISSUE TITLE
Publish - must specify a draft path

### ISSUE THREAD

**Issue by dsolodow** [jekyll/jekyll-compose#66]
When I run:
```sh
bundle exec jekyll publish
```
it returns:
jekyll 3.7.3 | Error:  You must specify a draft path.

However, running:
```sh
bundle exec jekyll draft "Test Post"
```
works find and creates the file in _drafts

**Comment by DirtyF** [comment]
You need to specify the draft you want to want to the `_posts` folder to publish it.
This command basically moves a file from the `_drafts` folder to the `_posts` folder.
