### ISSUE TITLE
Rename command

### ISSUE THREAD

**Issue by imabusabah** [jekyll/jekyll-compose#97]
At least for me, writing a title is the last step of the writing process. I start by having some idea of what I want to write but it always evolves over the course of actual writing. If I start by writing a title first, more often than not, I need to amend that title. In jekyll that means I need to change front matter and rename a file. Not the nicest IMO.

I'd like to be able to do something like `jekyll rename _drafts/untitled.md 'My Actual Title'`

When looking through the source code to see how this might be accomplished, I noticed that `Jekyll::Compose::ArgParser#validate!` returns a hard-coded error message if the argument list is empty, which complains that a name must be specified. Which is, of course, wouldn't work with a command that requires two arguments like a rename command. 

Do you think a rename command is worthwhile? If so, how would you handle the hard-coded error message?

Thanks.

**Comment by imabusabah** [comment]
I'm certainly glad my suggestion was taken up (#101). It would have been cool to have been in on it or at least acknowledged. Thanks.

**Comment by alzeih** [comment]
@imabusabah Hi! I wrote PR #101. I was waiting for a review from the jekyll team (I am not on this team) before tagging in this issue. If you have any feedback on the PR related to this issue I'd be glad to hear it. Thank you for the idea!

**Comment by alzeih** [comment]
PR #101 has been edited to note that it may close this issue. Can this issue please be reopened?
